### ISSUE TITLE
Patch script doesn't work correctly on linux

### ISSUE THREAD

**Issue by mnaamani** [Joystream/apps#10]
https://github.com/Joystream/apps/blob/fec15c9d22c6fc47c1d22ec92db01ac93e36f18f/package.json#L20

The script works fine on Mac, but not on linux.
```
yarn run v1.12.3
$ yarn patch && yarn build-ts
$ cp -a patches/ .
cp: 'patches/' and './patches' are the same file
error Command failed with exit code 1.
```

**Comment by jfinkhaeuser** [comment]
It's "cp -R patches/* ." at the moment, so I think this is no longer an issue.

**Comment by mnaamani** [comment]
Yes it was fixed in https://github.com/Joystream/apps/pull/45
