### ISSUE TITLE
Cannot restore account/key without password

### ISSUE THREAD

**Issue by jfinkhaeuser** [Joystream/apps#108]
It's perfectly possible to store accounts without password protection. The storage node does so in the signup process in order to allow for running the node without user interaction.

In the restore tab, though, it seems the minimum password length to unblock the button is 1. That means password-less accounts can never be restored.

**Comment by bwhm** [comment]
@jfinkhaeuser 
You can restore the account by entering the `mnemonic` or `raw seed` instead. You need to input a password, but it doesn't have to be the "old" one.

**Comment by jfinkhaeuser** [comment]
Yes, I know, @polkadot/api allows for either.
The JSON contains the key unencrypted, but serialized in a way that makes it non-intuitive to extract.

**Comment by bwhm** [comment]
Ok, good to know. I guess we should add an extra recovery option time permitting.

The `key` that is generated in the signup process is the one that is both staking and receiving payments? If so, we should at least include a file for converting in the storage repo.

**Comment by jfinkhaeuser** [comment]
Agreed.

**Comment by bwhm** [comment]
I would argue we could allow empty passphrases both when creating and recovering keys for testnet. Maybe just add a warning?

**Comment by siman** [comment]
Affected tabs:
- [ ] Create key
- [ ] Restore key
