### ISSUE TITLE
Nominators doesn't show up in Validator Overview

### ISSUE THREAD

**Issue by bwhm** [Joystream/apps#130]
Note that the `nominating` is actually working, it just won't show up in the Validator Overview.
Also note that this is confirmed for both `Schnorrkel` and `Edwards` keys
 
It can be confirmed that the `nominating` is working in three ways:
1. The `validator` that is nominated will be ordered correctly in terms of bonded tokens. If a `validator-stash` has bonded 5000, tokens and is nominated by another `nominator-stash` with  5000 bonded tokens, it will appear above a `validator` that has bonded 7000 tokens without any nominators.
2. Chain state -> staking -> stakers(accountID) (with the `validator-stash` address), will correctly list all the `nominator-stash` addresses that is nominating it.
3. Chain state -> staking -> nominators(AccountId) (with the `nominator-stash` address) will list the the `validator-stash` address, and the `nominator-stash` addresses that has bonded less (as "previous") and more (as "next"). 

Screenshot below shows chain state queries. The pasted addresses denotes the address used as `AccountID`.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/35237943/56319881-16948700-6163-11e9-85cb-9d7367868cae.png">

**Comment by bwhm** [comment]
Not sure if this is worth dealing with. I have not checked if it's a known bug upstream.

**Comment by mnaamani** [comment]
I think it has been fixed upstream? https://github.com/polkadot-js/apps/commit/b63583168baac9231211aa1b46cf66becbb3615e

**Comment by mnaamani** [comment]
Fixed in #137
