### ISSUE TITLE
Error while uploading a video file 

### ISSUE THREAD

**Issue by finnyfound** [Joystream/apps#144]
Error
![image](https://user-images.githubusercontent.com/31723998/56420011-f1fef300-62b9-11e9-8f78-794279a50486.png)

Dev tools screenshot
![image](https://user-images.githubusercontent.com/31723998/56419993-e6133100-62b9-11e9-9655-a879f75e187f.png)

_pasting the json as asked._
makeExtrinsicCall: updated status :: {"events":[{"phase":{"ApplyExtrinsic":2},"event":{"index":"0x0001","data":[]}}],"status":{"Finalized":"0xe189be7de37e7490922fbafda0cde9582900394536218155654cbde345693247"}}

**Comment by siman** [comment]
Thank you for reporting this!

**Comment by siman** [comment]
I believe this should not be an issue with the updated version of the storage node and how we create a new id for uploaded content: we generate it the same way as new account key pair is generated with the elliptic curve.
