### ISSUE TITLE
Forum User Stories

### ISSUE THREAD

**Issue by siman** [Joystream/apps#191]
This issue covers the user stories for the Forum module that we would like to see implemented in Acropolis release.

### All (members + non-members)

- [x] As a user I can view a list of top level topic categories.
- [x] As a user I can open topic categories and view threads, by title and date of submission, and subtopic categories.
- [x] As a user I can view a paginated list of posts in a thread.
- [x] As a user I can view a post, in terms of author, date of submission and text

### Member

- [x] As a member I can create a new thread in a category, with a title and text.
- [x] As a member I can compose a post in markdown and submit to a thread.
- [x] As a member I can edit the text of a post.

### Forum Sudo

- [ ] As forum sudo create a subcategory.
- [ ] As forum sudo I can delete a post.
- [ ] As forum sudo I can delete a category.

### Sudo

- [ ] As sudo I can make a member a forum sudo.
- [ ] As sudo I can remove a forum sudo.

**Comment by bedeho** [comment]
- As a user I can view a list of top level topic categories.
  - [x] Pioneer
  - [ ] Runtime

**Comment by siman** [comment]
Moved this issue to joystream repo: https://github.com/Joystream/joystream/issues/47
