### ISSUE TITLE
Restore schnorkkel from JSON imports as Edwards

### ISSUE THREAD

**Issue by bwhm** [Joystream/apps#201]
How to reproduce:

1. Generate `Schnorrkel` key (only tried w/password)
2. Save .JSON
3. Restore key

apps will import correct address, but interpret it as an `Edwards` key. When trying to send a tx, it fails with `1010`.

**Comment by mnaamani** [comment]
We did have an issue for that already https://github.com/Joystream/apps/issues/131
We did attempt to fix it at one point, but updating a dependency which had the fix, but it broke other things. So we reverted and instead my default key generation to be Edwards to try to avoid it. We should probably revisit though.

**Comment by bwhm** [comment]
Thanks! I remembered it as being the other way around, and thought our solution had just reversed the problem.
