### ISSUE TITLE
Testing results - Curator Hiring flow

### ISSUE THREAD

**Issue by bwhm** [Joystream/apps#269]
I will make a separate issue in the runtime repo, and add a link to that later.

## Generic Problems

- First of all, Pioneer is quite slow in the `Working Groups` sidebar. This is unfortunate, but not sure if anything can be done before we have a query node.

- Before anyone is hired, Pioneer shows `memberId` 0 as lead, not `memberId` 271. Not sure why, but might be related to this chain state query?
```
contentWorkingGroup.leadById: (Lead, Linkage<LeadId>)
[[0],[{"role_account":"5HEmrGvKCV12DtufgnF4LSSWPGZUPsvacLgi6UF73oWMeH9C","reward_relationship":null,"inducted":264,"stage":{"Active":null}}]]
```
- After the first hire, Pioneer shows this person as the lead. So this probably makes the assumption above wrong.

## Creating a new role

- Creating a new role with extrinsics breaks Pioneer. If one tries to change any of the dropdowns, it either fails to change, or freezes. This leads to only being able to test the defaults test cases.

## Applying for roles with a fixed number of slots

When you apply, Pioneer makes mistakes in ordering the applications. This bug probably affects multiple cases, but only the ones tested are listed below:

- For Test Case N, Pioneer assumes you are sorted by your `Application stake`, whereas the runtime orders by `Total Stake`.

- For Test Case P, Pioneer doesn't tell you that 10 is the max, but instead shows this screen (might be ok, but a bit strange):

![Screen Shot 2020-02-25 at 13 44 25](https://user-images.githubusercontent.com/35237943/75255944-09b0dd00-57e3-11ea-8bdc-2dc21e97260c.png)

The runtime will not accept this application though.

- For Test Case P, Pioneer sorts you correctly if you stake more than minimum, but if you stake less than minimum, it seems to assume this is extra stake. However, the runtime correctly identifies the stake as insufficient:

![Screen Shot 2020-02-25 at 13 46 48](https://user-images.githubusercontent.com/35237943/75256392-b1c6a600-57e3-11ea-9880-c31e01207e51.png)

## Processing/waiting after applying

Not sure if this is a bug, but it is a little confusing for users to have to choose the generated key instead of member key to see what your application status is.

There are some actual bugs though, especially wrt to sorting, all from Test Case P:

- This shows a situation where the applicant was pushed out (and stake returned), but Pioneer still treated it like it was part of the 10:
![2020-02-25 15 34 49](https://user-images.githubusercontent.com/35237943/75256838-64970400-57e4-11ea-93a6-c5dbd5dc4061.jpg)

- This shows a situation where the applicant was among the 10 included in the review period, but didn't get the job (probably ok?):
![2020-02-25 15 34 29](https://user-images.githubusercontent.com/35237943/75256844-66f95e00-57e4-11ea-9ed2-48dac6572a5b.jpg)

- This shows a situation where the applicant was among the 10 included in the review period, and got the job, but Pioneer thinks it was discarded for the review period, but got the job:
![2020-02-25 15 34 16](https://user-images.githubusercontent.com/35237943/75256853-68c32180-57e4-11ea-923b-35d126edd957.jpg)

---

Will add more later

**Comment by yourheropaul** [comment]
I'm going to close this issue, because it's been split into small issues.
