### ISSUE TITLE
Initial member for the curators goups

### ISSUE THREAD

**Issue by yourheropaul** [Joystream/apps#277]
The initial chain state seems to appoint one member, role account `5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM`, as the only member of the content curators, and there is no lead set.

Once the first hire is made via an opening, this member is replaced with whoever was hired.

Where does this account come from and why is it there?

**Comment by sergeibadass** [comment]
hi have you figured out where the account come from? is there a private key to this account? 

It is also in all Babe calls.
