### ISSUE TITLE
Pioneer - Content/channel issues

### ISSUE THREAD

**Issue by bwhm** [Joystream/apps#295]
This issue is meant to cover only UI/UX issues in pioneer:

### Needs fix:

- [ ] A new channel defaults to being `unlisted`. We should either change this (runtime), or let the user know that they need to await approval from curator before it gets listed. (I prefer the former, @mnaamani ?)
- [ ] Channel avatar/thumbnail is square, but is presented as "widescreen"
- [ ] Define channel banner format, and consider changing to same as YT?

### Low priority

- [ ] If you set the optional fields in `Create Channel`, and later want them set as blank, this doesn't seem to work (neither with extrinsics tab or UI)

### Needs fix:

- [ ] Google Chrome (probably also chromium++) results in “aw snap” error when attempting to upload videos above >150 MB.
- [ ] When uploading new Videos, `Link` (in_class_index=6), is not included in the tx (I assume it's being parsed as a `Text` prop, not `TextVec`.
- [x] When editing Videos, `License`, `Category` and `Link`, are not rendered.

WIP....

**Comment by mnaamani** [comment]
**A new channel defaults to being unlisted**
The channel publication status is actually an argument to the extrinsic call to create_channel() so we can control from pioneer what the default status on creation will be.
And as far as I can see it should be getting created with status Public, not Unlisted:

https://github.com/Joystream/apps/blob/d7dd699c9b5f86e74ef7672a2f7d6c9d114b4fdb/packages/joy-media/src/channels/EditChannel.tsx#L79

Is that not being reflected correctly in the UI ?

**Comment by bwhm** [comment]
> **A new channel defaults to being unlisted**
> The channel publication status is actually an argument to the extrinsic call to create_channel() so we can control from pioneer what the default status on creation will be.
> And as far as I can see it should be getting created with status Public, not Unlisted:
> 
> https://github.com/Joystream/apps/blob/d7dd699c9b5f86e74ef7672a2f7d6c9d114b4fdb/packages/joy-media/src/channels/EditChannel.tsx#L79
> 
> Is that not being reflected correctly in the UI ?

It's a different status - namely `curatorStatus` that defaults to unlisted...
See image sequence:

Creating channel:
![Screen Shot 2020-03-07 at 17 46 07](https://user-images.githubusercontent.com/35237943/76147392-1f07f000-609c-11ea-83f1-0c8a2a7bc758.png)

Status:
![Screen Shot 2020-03-07 at 17 46 28](https://user-images.githubusercontent.com/35237943/76147393-20391d00-609c-11ea-9381-1b91e33db7dc.png)

Curator making public:
![Screen Shot 2020-03-07 at 17 47 10](https://user-images.githubusercontent.com/35237943/76147396-216a4a00-609c-11ea-9800-634173bd23c4.png)

New status:
![Screen Shot 2020-03-07 at 17 47 28](https://user-images.githubusercontent.com/35237943/76147397-229b7700-609c-11ea-9576-8bce812af0d9.png)
