### ISSUE TITLE
Create a "Help & Info" section in the sidebar.

### ISSUE THREAD

**Issue by bwhm** [Joystream/apps#35]
There are some recurring questions and information that would be nice to reach all "users" without requiring them to contact us. Adding a new section available from the sidebar named "Help & Info" could be a quick way of allowing more users to get the information they need without too much effort.

The page could be divided into different sections, such as:
* Validators
* Elections and Voting
* Bugs Reporters
* News and guides

There should also be some stats that needs to go in there (static on top?)
* Information on next payouts for validators (A block height + time in GMT).
* More readable way of knowing when the next x, y and z part of the election is.
* Deadline to supply your xmr address to qualify for payment

**Comment by bwhm** [comment]
## Validators
**First validator payout will take place Thursday at noon GMT (block height ~ `79300`).** 
Make sure you have provided us with your monero address before that:
1. Preferably by setting your `memo` under the `My memo` tab in the `My accounts` sidebar. Example format: "4or8MyLongMoneroAddressInDoubleQuotes". Note that you can now do this despite having your funds staked.
2. Alternatively by following these [instructions](https://blog.joystream.org/p/dbbfe66d-4af3-42f3-93fb-9cde97721988/).
Please note that we prefer the former, and if you have done both (with different addresses), `1` will supersede `2`.

In another note, we have successfully upgraded the runtime, so you can now `unstake` your funds if you want to stop validating without getting slashed. Just note that you have to wait for one more `era` to complete before you can safely shut down your validator node (you will then be removed from the list of validators).

**Comment by bwhm** [comment]
## Elections and Voting
**First Council Election cycle will start at noon GMT (block height ~65,000).**
Follow the instructions in our [blog](https://blog.joystream.org/sparta/#council-member) on how to apply, vote, and reveal. If you are elected, remember set your `memo` field as described in the Validators section above in order to claim your reward!

**Comment by bwhm** [comment]
## Bug Reporters
**Bug Reports are always welcome.**
As a bounty for improving our software, rewards will be provided in proportion to the severity and quality of the `Issue` reported, or `Pull request` made. More information can be found [here](https://blog.joystream.org/sparta-incentives-structure/#bug-report).

**Comment by bwhm** [comment]
## News and guides
*This section will be updated regularly*
#### Successful runtime upgrade on  block height `n`
To fix the bug that kept Validators from performing a successful `unstake` transaction, and allow the `memo` to be updated while staking, we have made a "runtime upgrade". This changes the consensus code in-flight without a hard-fork. One of the wonderful features of the [Substrate](https://github.com/paritytech/substrate) framework is allowing these upgrades without forcing nodes to upgrade.
##### Guides and information
In our [blog](https://blog.joystream.org/), we have written some posts about our Sparta, and future testnets.
Find out more about [why](https://blog.joystream.org/pay-for-play/) are paying users in [monero](https://ww.getmonero.org/) to participate, [how](https://blog.joystream.org/sparta-incentives-structure/) you can contribute, and [what](https://blog.joystream.org/sparta/) you have to do to qualify.

**Comment by siman** [comment]
> **First validator payout will take place Thursday at noon GMT (block height ~ `93800`).**
better to specify an exact date like `Thursday, March 7, 2019, at 12 AM GMT`

**Comment by bwhm** [comment]
Agreed. Will re-write after setting up the accounts!
